fashion_mnist_labels = {
    'T-shirt/top': 0,
    'Trouser': 1,
    'Pullover': 2,
    'Dress': 3,
    'Coat': 4,
    'Sandal': 5,
    'Shirt': 6,
    'Sneaker': 7,
    'Bag': 8,
    'Ankle boot': 9
}

cifar10_labels = {
    'airplane': 0,
    'automobile': 1,
    'bird': 2,
    'cat': 3,
    'deer': 4,
    'dog': 5,
    'frog': 6,
    'horse': 7,
    'ship': 8,
    'truck': 9
}

gtsrb_labels = {
    'limit 20km/h': 0,
    'limit 30km/h': 1,
    'limit 50km/h': 2,
    'limit 60km/h': 3,
    'limit 70km/h': 4,
    'limit 80km/h': 5,
    'end of limit 80km/h': 6,
    'limit 100km/h': 7,
    'limit 120km/h': 8,
    'no passing': 9,
    'no passing for trucks': 10,
    'right-of-way next intersection': 11,
    'priority road': 12,
    'yield': 13,
    'stop': 14,
    'no way': 15,
    'no way for trucks': 16,
    'no way one-way': 17,
    'caution general': 18,
    'caution curve left': 19,
    'caution curve right': 20,
    'caution curvy': 21,
    'caution bumps': 22,
    'caution slippery': 23,
    'caution narrow road': 24,
    'road work': 25,
    'traffic signals': 26,
    'pedestrians': 27,
    'children crossing': 28,
    'bicycles crossing': 29,
    'ice/snow': 30,
    'wild animals crossing': 31,
    'end of speed and passing limits': 32,
    'turn right ahead': 33,
    'turn left ahead': 34,
    'ahead only': 35,
    'go straight or right': 36,
    'go straight or left': 37,
    'keep right': 38,
    'keep left': 39,
    'roundabout': 40,
    'end of no passing': 41,
    'end of no passing for trucks': 42
}